name: run workflow

on:
    workflow_dispatch

jobs:
    run_ordinary_workflow:
        name: run ordinary workflow
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write
        steps:
            - name: check out repo
              uses: actions/checkout@v4
            - name: run workflow
              uses: snakemake/snakemake-github-action@v1
              with:
                directory: './'
                snakefile: 'workflows/ordinary.smk'
                args: '--cores all -p'
                stagein: 'grep "model name" /proc/cpuinfo | uniq;free -h'

    run_checkpoint_workflow:
        name: run checkpoint workflow
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write
        steps:
            - name: check out repo
              uses: actions/checkout@v4
            - name: run workflow
              uses: snakemake/snakemake-github-action@v1
              with:
                directory: './'
                snakefile: 'workflows/checkpoint.smk'
                args: '--cores all -p'
                stagein: 'grep "model name" /proc/cpuinfo | uniq;free -h'